import callOfDuty from './call_of_duty.jpeg'

const data = {
  productData: [
    {
      id: 1,
      img: callOfDuty,
      title: 'CALL OF DUTY: MODERN WARFARE 2 - PS5 (PRE-OWNED)',
      desc: 'Activision',
      price: 2199,
    },
    {
      id: 2,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1934",
      title: "THE LAST OF US PART I - PS5 (PRE-OWNED)",
      desc:  "Electronics",
      price: 2799,
    },
    {
      id: 3,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_73",
      title: "GHOST OF TSUSHIMA - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 1649,
    },
    {
      id: 4,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1182",
      title: "GRAND THEFT AUTO V PREMIUM EDITION - PS4",
      desc: "Electronics",
      price: 1999,
    },
    {
      id: 5,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1604",
      title: "HORIZON FORBIDDEN WEST - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 2099,
    },
    {
      id: 6,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_106",
      title: "MARVEL'S SPIDERMAN - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 1299,
    },
    {
      id: 7,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1523",
      title: "GHOST OF TSUSHIMA - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 2299,
    },
    {
      id: 8,
      img: "http://localhost:3000/static/media/EA_2907.e2740f47ccd90d5ddd26.jpeg",
      title: "FIFA 23 - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 2299,
    },
    {
      id: 9,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_163",
      title: "UNCHARTED 4 A THIEFS END - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 899,
    },
    {
      id: 10,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4282",
      title: "STELLAR BLADE - PS5",
      desc: "Electronics",
      price: 4999,
    },
    {
      id: 11,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_3949",
      title: "MARVEL'S SPIDER-MAN 2 - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 4099,
    },
    {
      id: 12,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4088",
      title: "CYBERPUNK 2077: ULTIMATE EDITION - PS5",
      desc: "Electronics",
      price: 3999,
    },
    {
      id: 13,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4161",
      title: "RISE OF THE RONIN - PS5",
      desc: "Electronics",
      price: 4899,
    },
    {
      id: 14,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_3917",
      title: "ASSASSIN'S CREED MIRAGE - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 2699,
    },
    {
      id: 15,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4156",
      title: "AVATAR: FRONTIERS OF PANDORA - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 2899,
    },
    {
      id: 16,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_3954",
      title: "THE CREW MOTORFEST SPECIAL EDITION - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 3499,
    },
    {
      id: 17,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4268",
      title: "SONY PLAYSTATION 5 SLIM DISC EDITION 1TB - PS5",
      desc: "Sony",
      price: 54990,
    },
    {
      id: 18,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1240",
      title: "MADDEN NFL 21 - XBOX ONE (PRE-OWNED)",
      desc: "Electronics",
      price: 3999,
    },
    {
      id: 19,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1085",
      title: "SONY PLAYSTATION 4 PLATINUM WIRELESS HEADSET - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 9999,
    },
    {
      id: 20,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1786",
      title: "F1 2022 - XBOX SERIES X (PRE-OWNED)",
      desc: "Electronics",
      price: 3799,
    },
    {
      id: 21,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1128",
      title: "XBOX ONE CONTROLLER (3RD GEN) GREY & GREEN - XBOX ONE (PRE-OWNED)",
      desc: "Electronics",
      price: 4199,
    },
    {
      id: 22,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1717",
      title: "NINTENDO SWITCH OLED MODEL RED AND NEON BLUE - NINTENDO SWITCH (PRE-OWNED)",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 23,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1872",
      title: "SONY PLAYSTATION 4 PRO 1 TB (BODY DAMAGE) BLACK - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 24999,
    },
    {
      id: 24,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4268",
      title: "SONY PLAYSTATION 5 SLIM DISC EDITION 1TB - PS5",
      desc: "Electronics",
      price: 54990,
    },
    {
      id: 25,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4210",
      title: "ELDEN RING: SHADOW OF THE ERDTREE EDITION - PS5",
      desc: "Electronics",
      price: 4499,
    },
    {
      id: 26,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4209",
      title: "F1 24 - PS5",
      desc: "Electronics",
      price: 4999,
    },
    {
      id: 27,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_4213",
      title: "MOTOGP 24 - PS5",
      desc: "Electronics",
      price: 3999,
    },
    {
      id: 28,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1085",
      title: "SONY PLAYSTATION 4 PLATINUM WIRELESS HEADSET - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 9999,
    },
    {
      id: 29,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_976",
      title: "SONY PLAYSTATION 5 STANDARD EDITION 825 GB - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 52999,
    },
    {
      id: 30,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1058",
      title: "MICROSOFT XBOX SERIES S 512GB - XBOX SERIES X (PRE-OWNED)",
      desc: "Electronics",
      price: 3199,
    },
    {
      id: 31,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1595",
      title: "SONY PLAYSTATION 5 OFFICIAL DUAL SENSE CONTROLLER MIDNIGHT BLACK - PS5",
      desc: "Electronics",
      price: 5999,
    },
    {
      id: 32,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1086",
      title: "SONY PLAYSTATION 5 OFFICIAL DUAL SENSE CONTROLLER WHITE - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 4999,
    },
    {
      id: 33,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_998",
      title: "SONY PLAYSTATION 4 SLIM 500 GB JET BLACK - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 26999,
    },
    {
      id: 34,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_999",
      title: "NINTENDO SWITCH OLED MODEL RED AND NEON BLUE - NINTENDO SWITCH (PRE-OWNED)",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 35,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1596",
      title: "SONY PLAYSTATION 5 OFFICIAL DUAL SENSE CONTROLLER COSMIC RED (PRE-OWNED)",
      desc: "Electronics",
      price: 9999,
    },
    {
      id: 36,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1128",
      title: "XBOX ONE CONTROLLER (3RD GEN) GREY & GREEN - XBOX ONE (PRE-OWNED)",
      desc: "Electronics",
      price: 4199,
    },
    {
      id: 37,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_3884",
      title: "PLAYSTATION VR 2 - PS5 (PRE-OWNED)",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 38,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_4051",
      title: "DUAL SENSE EDGE WIRELESS CONTROLLER",
      desc: "Electronics",
      price: 22999,
    },
    {
      id: 39,
      img: "https://relay-bl-in-records.sgp1.cdn.digitaloceanspaces.com/GameNation/EA_1058",
      title: "MICROSOFT XBOX SERIES S 512GB - XBOX SERIES X (PRE-OWNED)",
      desc: "Electronics",
      price: 31999,
    },
    {
      id: 40,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1073",
      title: "SONY PLAYSTATION MOVE MOTION CONTROLLER V5",
      desc: "Electronics",
      price: 26999,
    },
    {
      id: 41,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1076",
      title: "LOGITECH G29 DRIVING FORCE RACING WHEEL",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 42,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1437",
      title: "XBOX SERIES CONTROLLER PULSE RED",
      desc: "Electronics",
      price: 23999,
    },
    {
      id: 43,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1511",
      title: "XBOX SERIES CONTROLLER DAYSTRIKE",
      desc: "Electronics",
      price: 21999,
    },
    {
      id: 44,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1151",
      title: "NINTENDO SWITCH RIGHT JOY CON NEON RED",
      desc: "Electronics",
      price: 21999,
    },
    {
      id: 45,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1152",
      title: "NINTENDO SWITCH RIGHT JOY CON NEON BLUE",
      desc: "Electronics",
      price: 17999,
    },
    {
      id: 46,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_3132",
      title: "NINTENDO SWITCH DOCK-NINTENDO SWITCH (PRE-OWNED)",
      desc: "Electronics",
      price: 54990,
    },
    {
      id: 47,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_3321",
      title: "OCULUS GUEST 2 256GB PC COMPONENTS (PRE-OWNED)",
      desc: "Electronics",
      price: 54990,
    },
    {
      id: 48,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_3004",
      title: "SAMSUNG M7 UHD 4K HIGH RESOLUTION",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 49,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2173",
      title: "MSI RTX 3050 8GB VENTUS 2X - PC COMPONENT",
      desc: "Electronics",
      price: 21399,
    },
    {
      id: 50,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_3049",
      title: "LG ULTRAGEAR - 27GP850 - 27 INCH WQHD 165HZ",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 51,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2559",
      title: "ZOTAC RTX 3080 10GB TRINITY",
      desc: "Electronics",
      price: 22999,
    },
    {
      id: 52,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1939",
      title: "ASUS RTX 2060 6GB DUAL - PC COMPONENTS",
      desc: "Electronics",
      price: 52999,
    },
    {
      id: 53,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1963",
      title: "ZOTAC RTX 2060 6GB (Pre-owned)",
      desc: "Electronics",
      price: 31999,
    },
    {
      id: 54,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1971",
      title: "COLORFUL RTX 2060 SUPER 8GB Ultra (Pre-owned)",
      desc: "Electronics",
      price: 5999,
    },
    {
      id: 55,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1975",
      title: "GALAX RTX 2060 SUPER 8GB 1-Click OC (Pre-owned)",
      desc: "Electronics",
      price: 4999,
    },
    {
      id: 56,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2006",
      title: "ASUS RTX 2070 8GB Dual (Pre-owned)",
      desc: "Electronics",
      price: 26999,
    },
    {
      id: 57,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2015",
      title: "GALAX RTX 2070 8GB EXOC (Pre-owned)",
      desc: "Electronics",
      price: 27999,
    },
    {
      id: 58,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2076",
      title: "GIGABYTE RTX 2070 SUPER 8GB G1 Gaming OC (Pre-owned)",
      desc: "Electronics",
      price: 23999,
    },
    {
      id: 59,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2092",
      title: "GALAX RTX 2080 8GB EX (Pre-owned)",
      desc: "Electronics",
      price: 21999,
    },
    {
      id: 60,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2178",
      title: "GIGABYTE RTX 3050 8GB Eagle OC (Pre-owned)",
      desc: "Electronics",
      price: 17999,
    },
    {
      id: 61,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2182",
      title: "ZOTAC RTX 3050 8GB Twin OC (Pre-owned)",
      desc: "Electronics",
      price: 54990,
    },
    {
      id: 62,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_2255",
      title: "Intel Core i3 10100F Processor (Pre-owned)",
      desc: "Electronics",
      price: 54990,
    },
    {
      id: 63,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1857",
      title: "SONY PLAYSTATION 4 SLIM 1 TB (BODY DAMAGE) GOLD - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 23999,
    },
    {
      id: 64,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_1826",
      title: "SONY PLAYSTATION 4 STANDARD 500GB (BODY DAMAGE) GLACIER WHITE - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 21999,
    },
    {
      id: 65,
      img: "https://sgp1.digitaloceanspaces.com/relay-bl-in-records/GameNation/EA_998",
      title: "SONY PLAYSTATION 4 SLIM 500 GB JET BLACK - PS4 (PRE-OWNED)",
      desc: "Electronics",
      price: 17999,
    },
  ]
};
export default data;